### ISSUE TITLE
Add presentation on contributing to k8s + CNCF ecosystem

### ISSUE THREAD

**Issue by caniszczyk** [cncf/presentations#13]
We need a general presentation outlining all the SIGs/WGs people can get involved with.

**Comment by nikhita** [comment]
I presented a lightning talk at KubeCon about contributing to Kubernetes: https://docs.google.com/presentation/d/1GUEJ2KUI0N8tvO7VOBB2sGU-hacQhvWSMs35swdW_SE/edit?usp=sharing. Do you think it would be a good idea to add it here (maybe a intro into it)? 

cc @luxas @idvoretskyi @jdumars

**Comment by idvoretskyi** [comment]
@nikhita yes, please submit a PR

**Comment by idvoretskyi** [comment]
Added Kubernetes Community Overview and Contributions Guide - https://github.com/cncf/presentations/commit/6a9da4b273cce0095af3e5117032286742edd5b5

We are good to close this issue now.
