### ISSUE TITLE
《了解 Kubernetes Master 的可扩展性和性能 》腾讯视频的源弄错了。能否更正一下

### ISSUE THREAD

**Issue by wykwdtc** [cncf/presentations#80]

**Comment by dankohn** [comment]
@donaldliu Can you please find the right URL and open a PR?

**Comment by donaldliu** [comment]
The concerned URL (video) on QQ is:
- https://v.qq.com/x/page/w0893a3ei5b.html
Note: While the cover page of the presentation (first 3 seconds) is correct, the video content then was not.

The corresponding English version (audio mainly in English via simultaneous translation, with Chinese hard to hear) on YouTube is:
- https://www.youtube.com/watch?v=1ThhTbMO1NE
- "Understanding Scalability and Performance in the Kubernetes Master - Xingyu Chen & Fansong Zeng", from KubeCon + CloudNativeCon + Open Source Summit China 2019

It will be wonderful to locate the correct video content with Chinese audio track by the speakers (which I need help), and put it on QQ, and then open a PR.

**Comment by donaldliu** [comment]
The right URL is https://v.qq.com/x/page/v0906j1czvd.html
Please refer to #81

**Comment by wykwdtc** [comment]
thanks
